source 'https://rubygems.org'

gem 'rails', '3.2.7'

gem 'jquery-rails', '~> 2.0.2'
gem 'mercury-rails', '~> 0.8.0'
gem 'paperclip', '~> 3.1.4'
gem 'sqlite3', '~> 1.3.6'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.11.0'
end

group :test do
  gem 'capybara', '~> 1.1.2'
  gem 'cucumber-rails', '~> 1.3.0', require: false
  gem 'database_cleaner', '~> 0.8.0'
end
